### ISSUE TITLE
Typo `superceded` should be `superseded`

### ISSUE THREAD

**Issue by CramBL** [joshrotenberg/adrs#39]
https://github.com/joshrotenberg/adrs/blob/1a68234a6399640e731bb051f9e82c1f37285d69/src/cmd/new.rs#L19

**Comment by lbenezriravin** [comment]
[supercede is actually a standard variant](https://ahdictionary.com/word/search.html?id=S5958400)

This spelling is consistent [with the reference implementation](https://github.com/npryce/adr-tools/blob/b3279baf9be2207d1a4f4bbd608fd0b591c72aee/src/adr-new#L5) as well, so it I think it makes sense to keep it.

**Comment by CramBL** [comment]
Fair enough. 

My reference for determining that it was an error was that it was flagged by https://github.com/crate-ci/typos and then I confirmed it with: https://www.merriam-webster.com/dictionary/supercede.

**Comment by joshrotenberg** [comment]
My main concern would be maintaining backwards compatibility for the command line options, but I'm open to addressing this because I hate typos or arguably incorrect usages too. I believe clap has a way to alias an argument so we could support both (maybe fix everything to the more common usage but support `supercede` with an alias. Either one of you up for a pull request?

**Comment by CramBL** [comment]
> My main concern would be maintaining backwards compatibility for the command line options, but I'm open to addressing this because I hate typos or arguably incorrect usages too. I believe clap has a way to alias an argument so we could support both (maybe fix everything to the more common usage but support `supercede` with an alias. Either one of you up for a pull request?

That sounds like a great solution to me. I could implement it tomorrow I expect.
